/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_emploi;

import javax.swing.JOptionPane;

/**
 *
 * @author Samir Souidi
 */
public class etudiant extends javax.swing.JFrame {

    /**
     * Creates new form etudiant
     */
     connexion cnx=new connexion();
    Class_etudiant etudiant=new Class_etudiant();
    public etudiant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        label_mat = new javax.swing.JLabel();
        checkd_matiere = new javax.swing.JCheckBox();
        list_classe_etud = new javax.swing.JComboBox<>();
        list_matiere_etud = new javax.swing.JComboBox<>();
        chercher_etud = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabl_seance_etud = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jours_list = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(230, 150));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("Espace etudiant");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-étudiant-homme-96.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Classe :");

        label_mat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_mat.setText("Matiere :");
        label_mat.setEnabled(false);

        checkd_matiere.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkd_matiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkd_matiereMouseClicked(evt);
            }
        });
        checkd_matiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkd_matiereActionPerformed(evt);
            }
        });

        list_classe_etud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:" }));
        list_classe_etud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_classe_etudActionPerformed(evt);
            }
        });
        list_classe_etud.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_classe_etudPropertyChange(evt);
            }
        });

        list_matiere_etud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:" }));
        list_matiere_etud.setEnabled(false);
        list_matiere_etud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_matiere_etudActionPerformed(evt);
            }
        });
        list_matiere_etud.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_matiere_etudPropertyChange(evt);
            }
        });

        chercher_etud.setBackground(new java.awt.Color(255, 255, 255));
        chercher_etud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chercher_etud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-chercher-18.png"))); // NOI18N
        chercher_etud.setText("Chercher");
        chercher_etud.setBorder(null);
        chercher_etud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercher_etudActionPerformed(evt);
            }
        });

        tabl_seance_etud.setAutoCreateRowSorter(true);
        tabl_seance_etud.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabl_seance_etud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabl_seance_etud.setFocusable(false);
        tabl_seance_etud.setRowHeight(30);
        jScrollPane4.setViewportView(tabl_seance_etud);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Jour :");

        jours_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tous les Jours :", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi" }));
        jours_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jours_listActionPerformed(evt);
            }
        });
        jours_list.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jours_listPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(list_classe_etud, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jours_list, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(checkd_matiere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_mat)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(list_matiere_etud, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(chercher_etud, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 26, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jours_list, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(list_classe_etud, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label_mat)
                                .addComponent(checkd_matiere))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chercher_etud, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(list_matiere_etud, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(445, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkd_matiereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkd_matiereMouseClicked
        // TODO add your handling code here:
        if(checkd_matiere.isSelected())
        {
            list_matiere_etud.setEnabled(true);
            label_mat.setEnabled(true);

        }
        else
        {
            list_matiere_etud.setEnabled(false);
            label_mat.setEnabled(false);
        }
    }//GEN-LAST:event_checkd_matiereMouseClicked

    private void checkd_matiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkd_matiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkd_matiereActionPerformed

    private void list_classe_etudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_classe_etudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_classe_etudActionPerformed

    private void list_classe_etudPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_classe_etudPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_classe_etudPropertyChange

    private void list_matiere_etudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_matiere_etudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_matiere_etudActionPerformed

    private void list_matiere_etudPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_matiere_etudPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_matiere_etudPropertyChange

    private void chercher_etudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercher_etudActionPerformed
        // TODO add your handling code here:
        try
        {
            String choix_classe=  list_classe_etud.getSelectedItem().toString();
              String choix_jour=  jours_list.getSelectedItem().toString();
            if(choix_classe =="Votre Choix:")
            {
                JOptionPane.showMessageDialog(null,"Svp choisir une classe:: ");

            }
            else {
                if(checkd_matiere.isSelected())
                {
                    String choix_matiere=  list_matiere_etud.getSelectedItem().toString();
                   
                    if(choix_matiere =="Votre Choix:")
                    {
                        JOptionPane.showMessageDialog(null,"Svp choisir une matiere ou décocher la recherche avec matière");

                    }
                    else {
                        /* requete recherche avec classe et matière*/
                        etudiant.chercher_et(tabl_seance_etud,choix_classe,choix_matiere,choix_jour);
                    }
                }
                else
                {

                    etudiant.chercher_et(tabl_seance_etud,choix_classe,"null",choix_jour);
                    /* requete pour recherche juste classe*/
                }

            }

            /*   String choix=  list_matricule.getSelectedItem().toString();
            PreparedStatement st =  cnx.connexion()
            .prepareStatement("UPDATE  enseignant "
                + "set nom='" + nom_action.getText() + "',contact= '" +
                contact_action.getText() + "' where matricule= '" + choix + "'");

            st.executeUpdate();

            JOptionPane.showMessageDialog(null,"Données modifié avec succès");
            */
        }

        catch(Exception e)
        {

        }
       
    }//GEN-LAST:event_chercher_etudActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          etudiant.loading(list_classe_etud, list_matiere_etud);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         this.setVisible(false);
                        index index = new index();
                        index.setTitle("Welcome");
                        index.setResizable(false);
                       
                        index.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jours_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jours_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jours_listActionPerformed

    private void jours_listPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jours_listPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jours_listPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkd_matiere;
    private javax.swing.JButton chercher_etud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jours_list;
    private javax.swing.JLabel label_mat;
    private javax.swing.JComboBox<String> list_classe_etud;
    private javax.swing.JComboBox<String> list_matiere_etud;
    private javax.swing.JTable tabl_seance_etud;
    // End of variables declaration//GEN-END:variables
}
