package gestion_emploi;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Achref
 */
public class manip_seance extends javax.swing.JFrame {

    /**
     * Creates new form manip_ensei
     */
    connexion cnx=new connexion();
    Seance C_seance=new Seance();
    public manip_seance() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabl_seance = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        label_mat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        list_seance = new javax.swing.JComboBox<>();
        label_classe1 = new javax.swing.JLabel();
        label_matiere1 = new javax.swing.JLabel();
        label_enseignant1 = new javax.swing.JLabel();
        label_jour1 = new javax.swing.JLabel();
        label_heuredeb1 = new javax.swing.JLabel();
        label_heurefin1 = new javax.swing.JLabel();
        ajouter6 = new javax.swing.JButton();
        ajouter4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        list_classe2 = new javax.swing.JComboBox<>();
        checkd_matiere = new javax.swing.JCheckBox();
        list_matiere = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabl_seance1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        matiere = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        list_enseignant_ajout = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        list_classe_ajout = new javax.swing.JComboBox<>();
        list_heuredebut = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        list_jour = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        list_heurefin = new javax.swing.JComboBox<>();
        label_classe = new javax.swing.JLabel();
        label_matiere = new javax.swing.JLabel();
        label_enseignant = new javax.swing.JLabel();
        label_jour = new javax.swing.JLabel();
        label_heuredeb = new javax.swing.JLabel();
        label_heurefin = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(150, 100, 0, 0));
        setLocation(new java.awt.Point(200, 200));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setFocusCycleRoot(true);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTabbedPane1.setOpaque(true);

        tabl_seance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabl_seance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_seance", "classe", "matiere", "jour", "heure", "matricule"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabl_seance.setPreferredSize(new java.awt.Dimension(1000, 600));
        tabl_seance.setRowHeight(30);
        jScrollPane5.setViewportView(tabl_seance);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("List des séance", jPanel1);

        jPanel8.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setText("Gestion séance");

        label_mat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_mat.setText("Matiere :");
        label_mat.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Id séance :");

        list_seance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        list_seance.setForeground(new java.awt.Color(255, 0, 0));
        list_seance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:" }));
        list_seance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_seanceActionPerformed(evt);
            }
        });
        list_seance.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_seancePropertyChange(evt);
            }
        });

        label_classe1.setForeground(new java.awt.Color(255, 0, 0));

        label_matiere1.setForeground(new java.awt.Color(255, 0, 0));

        label_enseignant1.setForeground(new java.awt.Color(255, 0, 0));

        label_jour1.setForeground(new java.awt.Color(255, 0, 0));

        label_heuredeb1.setForeground(new java.awt.Color(255, 0, 0));

        label_heurefin1.setForeground(new java.awt.Color(255, 0, 0));

        ajouter6.setBackground(new java.awt.Color(255, 255, 255));
        ajouter6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ajouter6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-chercher-18.png"))); // NOI18N
        ajouter6.setText("Chercher");
        ajouter6.setBorder(null);
        ajouter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter6ActionPerformed(evt);
            }
        });

        ajouter4.setBackground(new java.awt.Color(255, 255, 255));
        ajouter4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ajouter4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-poubelle-15.png"))); // NOI18N
        ajouter4.setText("Supprimer");
        ajouter4.setBorder(null);
        ajouter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Classe :");

        list_classe2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:" }));
        list_classe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_classe2ActionPerformed(evt);
            }
        });
        list_classe2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_classe2PropertyChange(evt);
            }
        });

        checkd_matiere.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkd_matiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkd_matiereMouseClicked(evt);
            }
        });
        checkd_matiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkd_matiereActionPerformed(evt);
            }
        });

        list_matiere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:" }));
        list_matiere.setEnabled(false);
        list_matiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_matiereActionPerformed(evt);
            }
        });
        list_matiere.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_matierePropertyChange(evt);
            }
        });

        tabl_seance1.setAutoCreateRowSorter(true);
        tabl_seance1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabl_seance1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabl_seance1.setFocusable(false);
        tabl_seance1.setRowHeight(30);
        jScrollPane4.setViewportView(tabl_seance1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addComponent(list_seance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ajouter4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(485, 485, 485)
                                .addComponent(label_jour1)
                                .addGap(253, 253, 253)
                                .addComponent(label_heuredeb1))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(label_matiere1)
                                        .addGap(217, 217, 217)
                                        .addComponent(label_enseignant1))
                                    .addComponent(label_classe1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_heurefin1)
                        .addGap(510, 510, 510))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(list_classe2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(checkd_matiere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_mat)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(list_matiere, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(ajouter6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label_mat)
                                .addComponent(jLabel11))
                            .addComponent(checkd_matiere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_classe2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajouter6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list_matiere, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(label_classe1)
                        .addGap(70, 70, 70)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_enseignant1)
                            .addComponent(label_matiere1)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label_heuredeb1)
                                .addComponent(label_heurefin1))
                            .addComponent(label_jour1)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list_seance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajouter4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actions ", jPanel11);

        jPanel6.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setText("Ajouter une séance");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Matiere :");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-annuler-18.png"))); // NOI18N
        jButton1.setText("Annuler");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ajouter.setBackground(new java.awt.Color(255, 255, 255));
        ajouter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-18.png"))); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.setBorder(null);
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Matricule enseignant :");

        list_enseignant_ajout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:" }));
        list_enseignant_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_enseignant_ajoutActionPerformed(evt);
            }
        });
        list_enseignant_ajout.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_enseignant_ajoutPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Classe :");

        list_classe_ajout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:" }));
        list_classe_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_classe_ajoutActionPerformed(evt);
            }
        });
        list_classe_ajout.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_classe_ajoutPropertyChange(evt);
            }
        });

        list_heuredebut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30" }));
        list_heuredebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_heuredebutActionPerformed(evt);
            }
        });
        list_heuredebut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_heuredebutPropertyChange(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Heure debut :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Jour :");

        list_jour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi" }));
        list_jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_jourActionPerformed(evt);
            }
        });
        list_jour.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_jourPropertyChange(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Heure Fin :");

        list_heurefin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Votre Choix:", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30" }));
        list_heurefin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_heurefinActionPerformed(evt);
            }
        });
        list_heurefin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                list_heurefinPropertyChange(evt);
            }
        });

        label_classe.setForeground(new java.awt.Color(255, 0, 0));

        label_matiere.setForeground(new java.awt.Color(255, 0, 0));

        label_enseignant.setForeground(new java.awt.Color(255, 0, 0));

        label_jour.setForeground(new java.awt.Color(255, 0, 0));

        label_heuredeb.setForeground(new java.awt.Color(255, 0, 0));

        label_heurefin.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list_classe_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_classe)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(list_jour, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label_jour))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(list_heuredebut, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(label_heuredeb)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_heurefin)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(list_heurefin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(matiere, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_matiere))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_enseignant)
                                    .addComponent(jLabel14)
                                    .addComponent(list_enseignant_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(221, 221, 221))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(list_classe_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label_classe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matiere, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list_enseignant_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_matiere)
                            .addComponent(label_enseignant)))
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(list_heuredebut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list_jour, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list_heurefin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_heuredeb)
                        .addComponent(label_heurefin))
                    .addComponent(label_jour))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajouter séance", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(735, 735, 735)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 42)); // NOI18N
        jLabel3.setText("Séance");

        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-classe-96.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jLabel18)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Session terminé");
        index log =new  index();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

       C_seance.loading(list_enseignant_ajout, list_seance,
           list_classe_ajout,  list_classe2, list_matiere,  tabl_seance);
   
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void list_matierePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_matierePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_matierePropertyChange

    private void list_matiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_matiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_matiereActionPerformed

    private void checkd_matiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkd_matiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkd_matiereActionPerformed

    private void checkd_matiereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkd_matiereMouseClicked
        // TODO add your handling code here:
        if(checkd_matiere.isSelected())
        {
            list_matiere.setEnabled(true);
            label_mat.setEnabled(true);

        }
        else
        {
            list_matiere.setEnabled(false);
            label_mat.setEnabled(false);
        }
    }//GEN-LAST:event_checkd_matiereMouseClicked

    private void list_classe2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_classe2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_classe2PropertyChange

    private void list_classe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_classe2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_classe2ActionPerformed

    private void ajouter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter4ActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        String choix=  list_seance.getSelectedItem().toString();
        if(choix =="Votre Choix:")
        {
            JOptionPane.showMessageDialog(null,"Svp choisir un id de séance");

        }
        else {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Voulez-vous supprimer cet séance", "Suppression", dialogButton);

            if(dialogResult == 0) {
                // Saving code here

               C_seance.delete_seance(choix);
                 list_seance.setSelectedItem("Votre Choix:");
               C_seance.update_table(tabl_seance);
                C_seance.update_list_seance(list_seance);
                C_seance.update_list_matiere(list_matiere);
                update_table_action();
            }

        }
    }//GEN-LAST:event_ajouter4ActionPerformed

    private void ajouter6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter6ActionPerformed
        // TODO add your handling code here:
        try
        {
            String choix_classe=  list_classe2.getSelectedItem().toString();
        if(choix_classe =="Votre Choix:")
        {
            JOptionPane.showMessageDialog(null,"Svp choisir une classe ");

        }
        else {
            if(checkd_matiere.isSelected())
            {
               String choix_matiere=  list_matiere.getSelectedItem().toString();
        if(choix_matiere =="Votre Choix:")
        {
            JOptionPane.showMessageDialog(null,"Svp choisir une matiere ou décocher la recherche avec matière");

        } 
        else {
            /* requete recherche avec classe et matière*/
            C_seance.chercher(tabl_seance1,choix_classe,choix_matiere);
        }
            }
            else 
            {
                 
               C_seance.chercher(tabl_seance1,choix_classe,"null");
                /* requete pour recherche juste classe*/
            }
            
        }

    
            /*   String choix=  list_matricule.getSelectedItem().toString();
            PreparedStatement st =  cnx.connexion()
            .prepareStatement("UPDATE  enseignant "
                + "set nom='" + nom_action.getText() + "',contact= '" +
                contact_action.getText() + "' where matricule= '" + choix + "'");

            st.executeUpdate();

            JOptionPane.showMessageDialog(null,"Données modifié avec succès");
            */
        }

        catch(Exception e)
        {

        }
        C_seance.update_table(tabl_seance);
    }//GEN-LAST:event_ajouter6ActionPerformed

    private void list_seancePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_seancePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_seancePropertyChange

    private void list_seanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_seanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_seanceActionPerformed

    private void list_heurefinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_heurefinPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_heurefinPropertyChange

    private void list_heurefinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_heurefinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_heurefinActionPerformed

    private void list_jourPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_jourPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_jourPropertyChange

    private void list_jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_jourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_jourActionPerformed

    private void list_heuredebutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_heuredebutPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_heuredebutPropertyChange

    private void list_heuredebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_heuredebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_heuredebutActionPerformed

    private void list_classe_ajoutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_classe_ajoutPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_classe_ajoutPropertyChange

    private void list_classe_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_classe_ajoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_classe_ajoutActionPerformed

    private void list_enseignant_ajoutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_list_enseignant_ajoutPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_list_enseignant_ajoutPropertyChange

    private void list_enseignant_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_enseignant_ajoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_enseignant_ajoutActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        String choix_classe=  list_classe_ajout.getSelectedItem().toString();
        String choix_enseignant=  list_enseignant_ajout.getSelectedItem().toString();
        String choix_jour=  list_jour.getSelectedItem().toString();
        String choix_heuredebut=  list_heuredebut.getSelectedItem().toString();
        String choix_heurefin=  list_heurefin.getSelectedItem().toString();

        try
        {
            if(choix_classe=="Votre Choix:" || choix_enseignant=="Votre Choix:" ||
                matiere.getText().equals("") || choix_jour=="Votre Choix:" ||
                choix_heuredebut=="Votre Choix:" ||  choix_heurefin=="Votre Choix:"    )
            {
                if(choix_classe=="Votre Choix:")
                {
                    label_classe.setText("Classe obligatoire");
                }
                else
                {
                    label_classe.setText("");
                }
                if(choix_enseignant=="Votre Choix:")
                {
                    label_enseignant.setText("Matricule obligatoire");
                }
                else{
                    label_enseignant.setText("");
                }

                if(matiere.getText().equals(""))
                {
                    label_matiere.setText("Matiere obligatoire");
                }else {
                    label_matiere.setText("");
                }

                if(choix_jour=="Votre Choix:")
                {
                    label_jour.setText("Jour obligatoire");
                }
                else{
                    label_jour.setText("");
                }
                if(choix_heuredebut=="Votre Choix:")
                {
                    label_heuredeb.setText("Heure obligatoire");
                }
                else{
                    label_heuredeb.setText("");
                }
                if(choix_heurefin=="Votre Choix:")
                {
                    label_heurefin.setText("Heure obligatoire");
                }
                else{
                    label_heurefin.setText("");
                }

            }
            else
            {

                /*verif si la matricule déja existe*/
                String heure=choix_heuredebut+" & "+choix_heurefin;
                C_seance.ajouter_seance(choix_classe,matiere.getText(), choix_jour, heure, choix_enseignant);
                list_classe_ajout.setSelectedItem("Votre Choix:");
                list_enseignant_ajout.setSelectedItem("Votre Choix:");
                list_jour.setSelectedItem("Votre Choix:");
                list_heuredebut.setSelectedItem("Votre Choix:");
                list_heurefin.setSelectedItem("Votre Choix:");
                matiere.setText("");

            }

        }
        catch(Exception e)
        {
            System.out.print(e);

        }
        C_seance.update_table(tabl_seance);
        C_seance.update_list_seance(list_seance);
        C_seance.update_list_matiere(list_matiere);

    }//GEN-LAST:event_ajouterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        matiere.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

private void update_table_action()
{
    try
    {

    }
    catch(Exception e)
    {
    }
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manip_ensei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manip_ensei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manip_ensei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manip_ensei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manip_ensei().setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton ajouter4;
    private javax.swing.JButton ajouter6;
    private javax.swing.JCheckBox checkd_matiere;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_classe;
    private javax.swing.JLabel label_classe1;
    private javax.swing.JLabel label_enseignant;
    private javax.swing.JLabel label_enseignant1;
    private javax.swing.JLabel label_heuredeb;
    private javax.swing.JLabel label_heuredeb1;
    private javax.swing.JLabel label_heurefin;
    private javax.swing.JLabel label_heurefin1;
    private javax.swing.JLabel label_jour;
    private javax.swing.JLabel label_jour1;
    private javax.swing.JLabel label_mat;
    private javax.swing.JLabel label_matiere;
    private javax.swing.JLabel label_matiere1;
    private javax.swing.JComboBox<String> list_classe2;
    private javax.swing.JComboBox<String> list_classe_ajout;
    private javax.swing.JComboBox<String> list_enseignant_ajout;
    private javax.swing.JComboBox<String> list_heuredebut;
    private javax.swing.JComboBox<String> list_heurefin;
    private javax.swing.JComboBox<String> list_jour;
    private javax.swing.JComboBox<String> list_matiere;
    private javax.swing.JComboBox<String> list_seance;
    private javax.swing.JTextField matiere;
    private javax.swing.JTable tabl_seance;
    private javax.swing.JTable tabl_seance1;
    // End of variables declaration//GEN-END:variables
}
